Repository AT-PHPIntership/booking-ticket, pull requests merged in 2018-07, with the labels that each got.

#1 Create template PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: in progress

#4 [Config] Config Circleci
  .circleci/config.yml
  app/Console/Kernel.php
  app/Exceptions/Handler.php
  app/Http/Controllers/Auth/RegisterController.php
  app/Http/Middleware/RedirectIfAuthenticated.php
  composer.json
  composer.lock
  phpcs.xml
  phpmd.xml
Labels: in progress

#6 [Migration] Create basic migrations
  .env.example
  composer.lock
  database/migrations/2018_07_24_013011_create_films_table.php
  database/migrations/2018_07_24_014225_create_users_table.php
  database/migrations/2018_07_24_015705_create_categories_table.php
  database/migrations/2018_07_24_020218_create_category_film_table.php
  database/migrations/2018_07_24_024327_create_bookings_table.php
  database/migrations/2018_07_24_027640_create_rooms_table.php
  database/migrations/2018_07_24_028255_create_schedules_table.php
  database/migrations/2018_07_24_030818_create_tickets_table.php
  database/migrations/2018_07_24_030955_create_seats_table.php
  database/migrations/2018_07_24_030956_create_booking_details_table.php
  database/migrations/2018_07_24_032250_create_images_table.php
  database/migrations/2018_07_24_032430_create_comments_table.php
  database/migrations/2018_07_24_032725_create_ratings_table.php
Labels: in progress, migration

#7 [Admin] layout for create user
  app/Http/Controllers/Admin/UserController.php
  resources/lang/en/user.php
  resources/views/admin/layout/sidebar.blade.php
  resources/views/admin/pages/users/create.blade.php
  routes/web.php
Labels: in progress

#12 [Admin] Create user
  app/Http/Controllers/Admin/UserController.php
  resources/lang/en/user.php
Labels: in progress

#15 [Admin] Layout and list user
  app/Http/Controllers/Admin/UserController.php
  composer.json
  composer.lock
  resources/lang/en/user.php
  resources/views/admin/layout/sidebar.blade.php
  resources/views/admin/pages/users/index.blade.php
  storage/debugbar/.gitignore
Labels: in progress

#14 create layout login
  app/Http/Controllers/HomeController.php
  resources/lang/en/login.php
  resources/views/auth/login.blade.php
  resources/views/home.blade.php
  resources/views/layouts/app.blade.php
  routes/web.php
Labels: in progress

#16 config dusk setup
  .circleci/config.yml
  .env.dusk.local
  .env.testing
  composer.json
  composer.lock
  config/database.php
  tests/Browser/ExampleTest.php
  tests/Browser/Pages/HomePage.php
  tests/Browser/Pages/Page.php
  tests/Browser/console/.gitignore
  tests/Browser/screenshots/.gitignore
  tests/DuskTestCase.php
Labels: in progress

#17 login, logout and middleware
  app/Http/Controllers/Auth/LoginController.php
  app/Http/Kernel.php
  app/Http/Middleware/AdminLoginMiddleware.php
  config/auth.php
  public/js/admin/popper.min.js
  resources/views/admin/layout/header.blade.php
  resources/views/admin/layout/master.blade.php
  routes/web.php
Labels: in progress

#18 Create category
  app/Http/Controllers/Admin/CategoryController.php
  app/Http/Requests/CreateCategoryRequest.php
  resources/lang/en/category.php
  resources/views/admin/pages/categories/create.blade.php
  routes/web.php
Labels: in progress

#22 show list update and delete category
  app/Http/Controllers/Admin/CategoryController.php
  config/define.php
  resources/views/admin/layout/sidebar.blade.php
  resources/views/admin/pages/categories/edit.blade.php
  resources/views/admin/pages/categories/index.blade.php
Labels: in progress

#21 [Admin] Delete user
  app/Http/Controllers/Admin/UserController.php
  resources/lang/en/user.php
  resources/views/admin/pages/users/index.blade.php
Labels: in progress, in review
