Repository AT-PHPIntership/booking-ticket, pull requests merged in 2018-08, with the labels that each got.

#23 Layout create film
  app/Http/Controllers/Admin/FilmController.php
  resources/lang/en/film.php
  resources/views/admin/layout/sidebar.blade.php
  resources/views/admin/pages/films/create.blade.php
  routes/web.php
Labels: in progress

#20 Test login logout
  app/Models/User.php
  app/Providers/AppServiceProvider.php
  database/factories/UserFactory.php
  tests/Browser/ExampleTest.php
  tests/Browser/LoginTest.php
  tests/DuskTestCase.php
Labels: in progress

#24 Create film
  app/Http/Controllers/Admin/FilmController.php
  app/Http/Requests/CreateFilmRequest.php
  app/Models/Category.php
  app/Models/Film.php
  public/images/upload/1533174231-8jhnm-anete-lusina-382329-unsplash.jpg
  public/js/admin/main.js
  resources/lang/en/film.php
  resources/views/admin/pages/films/create.blade.php
Labels: in progress

#27 Test create category
  database/factories/CategoryFactory.php
  database/migrations/2018_07_24_015705_create_categories_table.php
  tests/Browser/Admin/Category/CreateCategoryTest.php
  tests/Browser/Pages/Admin/Category/CreateCategoryPage.php
Labels: in progress

#25 show list film
  app/Http/Controllers/Admin/FilmController.php
  public/js/admin/list_film.js
  resources/views/admin/layout/sidebar.blade.php
  resources/views/admin/pages/films/index.blade.php
Labels: in progress

#35 show list, detail bookings and delete booking
  app/Http/Controllers/Admin/BookingController.php
  config/define.php
  resources/lang/en/booking.php
  resources/lang/en/master.php
  resources/views/admin/layout/sidebar.blade.php
  resources/views/admin/pages/bookings/index.blade.php
  resources/views/admin/pages/bookings/show.blade.php
  routes/web.php
Labels: in progress

#31 create factory and seed into database
  database/factories/BookingDetailFactory.php
  database/factories/BookingFactory.php
  database/factories/CategoryFilmFactory.php
  database/factories/CommentFactory.php
  database/factories/FilmFactory.php
  database/factories/ImageFactory.php
  database/factories/RatingFactory.php
  database/factories/RoomFactory.php
  database/factories/ScheduleFactory.php
  database/factories/SeatFactory.php
  database/factories/TicketFactory.php
  database/factories/UserFactory.php
  database/seeds/BookingDetailsTableSeeder.php
  database/seeds/BookingsTableSeeder.php
  database/seeds/CategoriesTableSeeder.php
  database/seeds/CategoryFilmsTableSeeder.php
  database/seeds/CommentsTableSeeder.php
  database/seeds/DatabaseSeeder.php
  database/seeds/FilmsTableSeeder.php
  database/seeds/ImagesTableSeeder.php
  database/seeds/RatingsTableSeeder.php
  database/seeds/RoomsTableSeeder.php
  database/seeds/SchedulesTableSeeder.php
  database/seeds/SeatsTableSeeder.php
  database/seeds/TicketsTableSeeder.php
  database/seeds/UsersTableSeeder.php
Labels: in progress, in review

#33 [Admin] List schedule in dasboard
  app/Http/Controllers/Admin/ScheduleController.php
  app/Http/Controllers/Admin/UserController.php
  config/define.php
  resources/lang/en/master.php
  resources/lang/en/schedule.php
  resources/views/admin/layout/sidebar.blade.php
  resources/views/admin/pages/schedules/index.blade.php
  resources/views/auth/layouts/app.blade.php
  routes/web.php
Labels: in progress, in review

#41 Show list ticket
  app/Http/Controllers/Admin/TicketController.php
  config/define.php
  resources/lang/en/master.php
  resources/lang/en/ticket.php
  resources/views/admin/layout/sidebar.blade.php
  resources/views/admin/pages/tickets/index.blade.php
  routes/web.php
Labels: in progress

#40 [Admin] Admin update schedule
  app/Http/Controllers/Admin/ScheduleController.php
  resources/lang/en/master.php
  resources/views/admin/pages/schedules/edit.blade.php
Labels: in progress, in review

#43 create update and deleted ticket
  app/Http/Controllers/Admin/TicketController.php
  app/Http/Requests/CreateTicketRequest.php
  app/Http/Requests/EditTicketRequest.php
  public/js/admin/add_ticket.js
  public/js/admin/main.js
  resources/lang/en/ticket.php
  resources/views/admin/pages/tickets/create.blade.php
  resources/views/admin/pages/tickets/edit.blade.php
  resources/views/admin/pages/tickets/index.blade.php
  routes/web.php
Labels: in progress

#44 layout index user
  app/Http/Controllers/Home/HomeController.php
  public/css/public/slider.css
  public/css/public/style.css
  public/font/Amble-Regular-webfont.ttf
  public/images/banner/1.jpg
  public/images/banner/2.jpg
  public/images/banner/3.jpg
  public/images/banner/4.jpg
  public/images/banner/5.jpg
  public/images/icon/arrow_up.png
  public/images/icon/arrows.png
  public/images/icon/btn-bg.png
  public/images/icon/compare.png
  public/images/icon/drop_arrow.png
  public/images/icon/facebook.png
  public/images/icon/linkedin.png
  public/images/icon/logo.png
  public/images/icon/search.png
  public/images/icon/skype.png
  public/images/icon/strip-bg.gif
  public/images/icon/twitter.png
  public/images/icon/wishlist.png
  public/js/public/easing.js
  public/js/public/jquery-1.9.0.min.js
  public/js/public/jquery.nivo.slider.js
  public/js/public/main.js
  public/js/public/move-top.js
  resources/lang/en/user/index.php
  resources/lang/en/user/layout.php
  resources/lang/en/user/title.php
  resources/views/public/layout/header.blade.php
  resources/views/public/layout/master.blade.php
  resources/views/public/pages/index.blade.php
  routes/web.php
Labels: in progress

#46 fix layout
  resources/views/public/layout/header.blade.php
  resources/views/public/layout/master.blade.php
  resources/views/public/layout/top.blade.php
  resources/views/public/pages/index.blade.php
  resources/views/public/pages/login.blade.php
  resources/views/public/pages/register.blade.php
Labels: in progress

#49 Api user category
  app/Http/Controllers/Api/User/CategoryController.php
  docs/api-references/category.md
  public/js/public/category.js
  resources/views/public/layout/header.blade.php
  routes/api.php
Labels: api, in progress

#50 [API] Create template job use queue to send mail
  app/Http/Controllers/Api/User/RegisterController.php
  app/Jobs/SendMailJob.php
  app/Mail/SendMail.php
  database/migrations/2018_08_17_013056_create_jobs_table.php
  resources/views/admin/pages/users/mail.blade.php
Labels: api, in progress

#51 layout implement api user register
  public/css/public/style.css
  public/js/public/jquery.validate.min.js
  public/js/public/register.js
  resources/lang/en/user/login.php
  resources/views/public/layout/master.blade.php
  resources/views/public/layout/top.blade.php
  resources/views/public/pages/register.blade.php
Labels: api

#53 [API] Show and update user info
  app/Http/Controllers/Api/User/UserController.php
  app/Http/Requests/User/UpdateUserRequest.php
  docs/api-references/user.md
  public/js/public/login.js
  routes/api.php
Labels: api, in progress

#54 [Api] Create api for user booking
  app/Http/Controllers/Api/User/BookingController.php
  app/Http/Requests/User/CreateBookingRequest.php
  app/Http/Requests/User/GetBookingRequest.php
  app/Http/Requests/User/ShowBookingRequest.php
  config/define.php
  docs/api-references/booking.md
  routes/api.php
Labels: api, in progress

#58 [API] Create api schedule for booking
  app/Http/Controllers/Api/User/ScheduleController.php
  docs/api-references/schedule.md
  routes/api.php
Labels: api, in progress

#65 [Fix bug] Fix search, layout in public page
  app/Http/Controllers/Api/User/FilmController.php
  public/css/public/style.css
  public/js/public/search.js
  resources/views/public/layout/header.blade.php
  resources/views/public/layout/master.blade.php
  resources/views/public/layout/top.blade.php
Labels: fix bug, in progress

#66 [Search] Add search in admin
  app/Http/Controllers/Api/Admin/SearchController.php
  app/Http/Controllers/Api/User/FilmController.php
  app/Http/Requests/SearchRequest.php
  public/css/admin/main.css
  public/css/public/style.css
  public/images/default/default-user.png
  public/js/admin/search.js
  resources/views/admin/layout/header.blade.php
  resources/views/admin/layout/master.blade.php
  routes/api.php
Labels: api, in progress
